version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: verse-arenadream
    restart: always
    ports:
      - "3000:3000"
    networks:
      - verse-arenadream-network

networks:
  verse-arenadream-network:
    driver: bridge 